version: '3'
services:
  geoserver:
    image: kartoza/geoserver:2.16.2
    depends_on:
      - postgis
    ports:
      - "8080:8080"
    environment:    
      - "SAMPLE_DATA=true"
    volumes:
      - geoserverdata:/opt/geoserver/data_dir
  postgis:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "25432:5432"
    environment:
      - "POSTGRES_USER=proyecto"
      - "POSTGRES_PASS=proyectovm"
      - "POSTGRES_DBNAME=proyectodb"
      - "DEFAULT_ENCODING=UTF8"
    volumes:
      - dbdata:/var/lib/postgresql      
volumes:
    geoserverdata:
        external: true
    dbdata:
        external: true    
